os: linux
dist: focal
language: minimal

addons:
  apt:
    update: true
    packages: [python3-pip, lcov, gcovr]

install:
  - pip3 install cpplint

jobs:
  include:
    - name: "checks"
      script: ./scripts/checks.sh
    - name: "tests"
      script: ./scripts/tests.sh
    - name: "quality"
      script: ./scripts/coverage.sh
      # The bot has gone...
      # - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false

branches:
  except:
    - master

cache:
  directories:
    - ~/.hunter
