os: linux
dist: bionic
language: minimal

compiler: gcc

addons:
  apt:
    update: true
    packages: [ python3-pip, gcovr ]

install:
  - pip3 install cpplint

jobs:
  include:
    - name: "checks"
      env: CACHE_NAME=checks
      script: ./scripts/checks.sh
    - name: "tests"
      env: CACHE_NAME=tests
      script: ./scripts/tests.sh
    - name: "quality"
      env: CACHE_NAME=coverage
      script: ./scripts/coverage.sh
      # The bot has gone...
      # - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false

branches:
  except:
    - master

cache:
  directories:
    - ~/.hunter
